name: Angular CI/CD

on:
  push:
    branches:
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Ensure Node.js version is at least 18

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular app
        run: npm run build

      - name: List directory contents after build
        run: ls -la dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Copy artifacts
        run: |
          mkdir -p deploy
          cp -r dist/* deploy/

      - name: Set up Node.js (if not already set up)
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Ensure Node.js version is at least 18

      - name: Install Angular CLI (if not already installed)
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Run Angular app
        run: npm start
